### PR TITLE
474 worker disabled flooding

### PR DESCRIPTION
**Pull request by bitfag**

### CODE REVIEW

**Comment by bitfag** [comment]
Need to do it a bit cleaner.

```
2019-04-06 14:16:21,254 (staggered_orders:319) - worker12 - DEBUG - Maintenance execution took: 1.26 seconds
2019-04-06 14:16:21,255 (worker:121) - worker12 - ERROR - Worker "worker12" is disabled

Error in on_block: OrderedDict mutated during iteration

Traceback (most recent call last):
  File "/home/vvk/.local/share/virtualenvs/DEXBot-prod-N9mtHQyI/lib/python3.6/site-packages/bitshares-0.2.1-py3.6.egg/bitsharesapi/websocket.py", line 276, in on_message
    [getattr(self.events, callbackname)(x) for x in data["params"][1]]
  File "/home/vvk/.local/share/virtualenvs/DEXBot-prod-N9mtHQyI/lib/python3.6/site-packages/bitshares-0.2.1-py3.6.egg/bitsharesapi/websocket.py", line 276, in <listcomp>
    [getattr(self.events, callbackname)(x) for x in data["params"][1]]
  File "/home/vvk/.local/share/virtualenvs/DEXBot-prod-N9mtHQyI/lib/python3.6/site-packages/Events-0.3-py3.6.egg/events/events.py", line 95, in __call__
    f(*a, **kw)
  File "/home/vvk/devel/DEXBot-prod/dexbot/worker.py", line 117, in on_block
    for worker_name, worker in self.config["workers"].items():
RuntimeError: OrderedDict mutated during iteration
```

**Comment by joelvai** [comment]
GUI: When trying to pause disabled worker gives following error 

> Traceback (most recent call last):
  File "/home/joel/projects/DEXBot/dexbot/views/errors.py", line 94, in func_wrapper
    return func(*args, **kwargs)
  File "/home/joel/projects/DEXBot/dexbot/views/worker_item.py", line 87, in pause_worker
    self.main_ctrl.pause_worker(self.worker_name)
  File "/home/joel/projects/DEXBot/dexbot/controllers/main_controller.py", line 58, in pause_worker
    self.worker_manager.stop(worker_name, pause=True)
  File "/home/joel/projects/DEXBot/dexbot/worker.py", line 209, in stop
    self.workers[worker_name].pause()
KeyError: 'Worker 1'

**Comment by PermieBTS** [comment]
@bitfag can you make sure to avoid adding feature-specific code to the base, which should be only for universally useful code

https://github.com/Codaone/DEXBot/pull/569
https://github.com/Codaone/DEXBot/pull/558

**Comment by bitfag** [comment]
@PermieBTS please comment in relevant issues/PRs.

**Pull request merged**
