### PR TITLE
#596 Properties fix

### LINKED ISSUE #596: BitsharesOrderEngine and BitsharesPriceFeed inconsistent attributes
BitsharesOrderEngine uses attributes which are not defined in `__init__` (or elsewhere):

* self.account
* self.market
* self.worker

This means methods which uses these attrs are broken on standalone BitsharesOrderEngine. Now we're don't noticing this because the only user of BitsharesOrderEngine is StrategyBase. All these attrs defined inside StrategyBase.

### PR DESCRIPTION
**Pull request by thehapax**
#596

### CODE REVIEW

**Comment by thehapax** [comment]
@bitProfessor just fyi i change structure slightly so that base doesn't override properties. Please adjust in Unit Test. thx.

**Comment by thehapax** [comment]
saw an error with balances property. working to fix this now.

**Comment by thehapax** [comment]
@bitProfessor some odd going on with the balances property in base and bitshares order engine. If removed from base, it creates infinite order place and cancel loop. I think possibly due to methods that depend on balances in inherited class. Have not had a look yet, but issue still needs to be resolved.

**Comment by bitProfessor** [comment]
What can I do?

On 06/22/2019 04:17, octomatic wrote:

@bitProfessor some odd going on with the balances property in base and bitshares order engine. If removed from base, it creates infinite order place and cancel loop. I think possibly due to methods that depend on balances in inherited class. Have not had a look yet, but issue still needs to be resolved.

**Comment by PermieBTS** [comment]
@thehapax

**Comment by thehapax** [comment]
@PermieBTS i'm thinking about it!

**Comment by thehapax** [comment]
> What can I do? On 06/22/2019 04:17, octomatic wrote: @bitProfessor some odd going on with the balances property in base and bitshares order engine. If removed from base, it creates infinite order place and cancel loop. I think possibly due to methods that depend on balances in inherited class. Have not had a look yet, but issue still needs to be resolved. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

I think for the BaseStrategy  - it needs to be modified so that we import the BitsharesOrderEngine and create an instance instead of inheriting it. its not really decoupled properly. For BitsharesPriceFeed, it can imported or inherited, the code split is ok

**Comment by bitProfessor** [comment]
OK, let me study it.




| |
Professor
|
|
bitprofessor@163.com
|
签名由网易邮箱大师定制


On 07/17/2019 04:44，octomatic<notifications@github.com> wrote：

What can I do? On 06/22/2019 04:17, octomatic wrote: @bitProfessor some odd going on with the balances property in base and bitshares order engine. If removed from base, it creates infinite order place and cancel loop. I think possibly due to methods that depend on balances in inherited class. Have not had a look yet, but issue still needs to be resolved. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

I think for the BaseStrategy - it needs to be modified so that we import the BitsharesOrderEngine and create an instance instead of inheriting it. its not really decoupled properly. For BitsharesPriceFeed, it can imported or inherited, the code split is ok

**Comment by bitProfessor** [comment]
hi @thehapax,I found that the devel branch is not up to date, should I fork your branch?

**Comment by thehapax** [comment]
> hi @thehapax,I found that the devel branch is not up to date, should I fork your branch?

I think its `git checkout -b thehapax:596-properties --set-upstream-to=codaone/devel`

followed by `git pull` to in order to update the branch. i believe you should be able to make commits directly, let me know if you can't

**Comment by thehapax** [comment]
FYI - i updated the branch @bitProfessor . You also have access to modify the branch now

**Comment by bitProfessor** [comment]
> FYI - i updated the branch @bitProfessor . You also have access to modify the branch now

okay

**Comment by bitProfessor** [comment]
> @bitProfessor some odd going on with the balances property in base and bitshares order engine. If removed from base, it creates infinite order place and cancel loop. I think possibly due to methods that depend on balances in inherited class. Have not had a look yet, but issue still needs to be resolved.



I tried to reproduce the error. Can you tell me which function is called specifically when I get the error?(I have run test_base.py, test_bitshares_engine.py)

**Comment by thehapax** [comment]
> > @bitProfessor some odd going on with the balances property in base and bitshares order engine. If removed from base, it creates infinite order place and cancel loop. I think possibly due to methods that depend on balances in inherited class. Have not had a look yet, but issue still needs to be resolved.
> 
> I tried to reproduce the error. Can you tell me which function is called specifically when I get the error?(I have run test_base.py, test_bitshares_engine.py)

If you remove the balances method from the base.py, i get the error. 

```
@property
    def balances(self):
        """ Returns all the balances of the account assigned for the worker.

            :return: Balances in list where each asset is in their own Amount object
        """
        return self._account.balances
```

**Comment by bitProfessor** [comment]
1、i remove the balances method from the base.py：
I run test_relative_orders_unittest.py, print out orders, and it looks all right.
2、 are u sure that no other threads are running in your environment?

**Comment by thehapax** [comment]
> 1、i remove the balances method from the base.py：
> I run test_relative_orders_unittest.py, print out orders, and it looks all right.
> 2、 are u sure that no other threads are running in your environment?

Does it work ok for SO as well? 
have no other threads running

**Pull request merged**
