### PR TITLE
515 test interface local testnet [waiting for xeroc]

### PR DESCRIPTION
**Pull request by bitfag**

### CODE REVIEW

**Comment by bitfag** [comment]
I forgot to mention, these changes rely on not-yet merged changes into pybitshares and pygraphene.

**Comment by thehapax** [comment]
> I forgot to mention, these changes rely on not-yet merged changes into pybitshares and pygraphene.

what are the changes and when can we expect them? Would xeroc be the the person responsible? @PermieBTS for follow up

**Comment by bitfag** [comment]
PRs references are here inside "In progress" https://github.com/Codaone/DEXBot/projects/10

* https://github.com/bitshares/python-bitshares/pull/223
* https://github.com/bitshares/python-bitshares/pull/224

Waiting for @xeroc

**Comment by xeroc** [comment]
> Waiting for @xeroc

both have been merged to develop. Do you need a release?

**Comment by bitfag** [comment]
@xeroc not necessary, there are still several issues to fix, like https://github.com/bitshares/python-bitshares/issues/234

**Comment by bitfag** [comment]
For @bitprofessor:

To try this now, you need to checkout my branch `515-test-interface-local-testnet` and manually switch pybitshares and pygraphene to `develop` versions. E.g.

```
cd ~/devel/python-bitshares
git checkout -b develop origin/develop
```

```
cd dexbot
pip install -e ~/devel/python-bitshares
```

Repeat for `python-graphenelib.

**Comment by bitProfessor** [comment]
Thanks


On 05/08/2019 22:49, Vladimir Kamarzin wrote:

For @bitProfessor:

To try this now, you need to checkout my branch 515-test-interface-local-testnet and manually switch pybitshares and pygraphene to develop versions. E.g.

cd ~/devel/python-bitshares
git checkout -b develop origin/develop

cd dexbot
pip install -e ~/devel/python-bitshares


Repeat for `python-graphenelib.

**Comment by bitProfessor** [comment]
hi @bitfag ,i need a docker daemon of bitshares-core testnet ,can you help me ?

**Pull request merged**
