### PR TITLE
Change market center price handling in profit methods

### PR DESCRIPTION
**Pull request by bitfag**
Methods to store or get profit estimation data are depends on
get_market_center_price(). When there is no bids or asks,
get_market_center_price() will disable the whole worker. This is not
needed when we just want to store/calc profits, so we can use
`suppress_errors=True` here safely.

Closes: #563

### CODE REVIEW

**Comment by thehapax** [comment]
If this change is for Staggered orders only the method should not be updated in base.py, It should be overridden in staggered orders.  I do not like the idea of forcing all strategies to inherit ```suppress_errors=True```

**Comment by bitfag** [comment]
This is not a strategy-specific change. The current method will break execution of **any** strategy in case of no bids or asks on the market. The problem is that `get_market_center_price()` forces worker to stop by default. To address your comment, I can add a `suppress_errors=True` kwarg to `store_profit_estimation_data()` and `calc_profit()`.

**Comment by bitfag** [comment]
I rethink this and it's seems wrong to add a `suppress_errors=True`. I propose to change logic a bit:

* store_profit_estimation_data() should not disable the whole worker at all
* store_profit_estimation_data() should not write data if `center price = 0`. This means we're just waiting until some orders will appear on the market
* calc_profit() should not not disable the whole worker at all
* calc_profit() should return 0 profit if `center price = 0`. Just wait for orders on market.

**Comment by thehapax** [comment]
@joelvai i'm not sure how you want to do the merge if we have the classes split in the base refactor. @bitfag Here is what i have so far; no pull yet as the one unit test not completed. Let me know if you want to do this merge first and then have me manually adjust or vice versa. Any suggestions welcome. 

https://github.com/thehapax/DEXBot/tree/542-base-refactor-part2

**Comment by bitfag** [comment]
I'll take a look after few days (some holidays here).

**Comment by bitfag** [comment]
Ok, I see that `devel` branch is already have changes to base.py applied. The goal is to not block whole development during refactor. The correct approach is to rebase/merge topic branch (`542-base-refactor-part2` in this case) on top of parent branch (`devel`) before creating a PR. There will be merge conflicts. I can help on merging/rebasing your work at the top of `devel` when you'll finish.

**Comment by thehapax** [comment]
Ok sounds good. I've been on vacation for a few days as well. Just returning today. Thanks @bitfag

**Pull request merged**
